### ISSUE TITLE
Hats don't get assigned a curios slot with FFApi (Duplicate)

### ISSUE THREAD

**Issue by Mqony** [fonnymunkey/SimpleHats#83] opened 2024-09-23 06:17 UTC
The mod basically combines Curios and the Trinkets mod into one interface. It is compatible with most mods that support Curios/Trinkets, though it seems to have issues with this mod. It uses compat layers of both Trinkets and Curios instead of the actual mods, which could be causing issues with this mod.

Mod List (Forge 1.20.1)
Simple Hats
Accessories Mod
Trinkets Compat Layer for Accessories
Curios Compat Layer for Accessories
Sinytra Connector
Forgified Fabric API

**Comment by fonnymunkey** [comment] 2024-09-23 06:43
SimpleHats works fine with Accessories from mine and others testing, the issue you are encountering is likely a duplicate of #82 which is FFApi breaking the Curio slot validation json, which happens regardless of Accessories.

As you are using Sinytra anyways, you can try using the Fabric version of SimpleHats with the Trinkets compat layer, as that uses a different method of slot validation than Curios and may avoid whatever issue FFApi is causing.

Otherwise if switching to the Fabric version isn't possible, then it is just up to waiting for Sinytra/FFApi to fix as as far as I can tell it is a problem on their end and not something I can reasonably fix on mine.

Closing as duplicate.

**Closed as completed by fonnymunkey** 2024-09-23 06:43 UTC

**Comment by Mqony** [comment] 2024-09-23 07:02
Switching to fabric worked, thanks!
